//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
namespace InterSystems.IHE.Client.IHE.XDSb {

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="DocumentRepository_Binding", Namespace="urn:ihe:iti:xds-b:2007")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryRequestType))]
public partial class DocumentRepository_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback DocumentRepository_RetrieveDocumentSetOperationCompleted;
    
    private System.Threading.SendOrPostCallback DocumentRepository_ProvideAndRegisterDocumentSetbOperationCompleted;
    
    /// <remarks/>
    public DocumentRepository_Service() {
        this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
        this.Url = "http://servicelocation/DocumentRepository_Service";
    }
    
    /// <remarks/>
    public event DocumentRepository_RetrieveDocumentSetCompletedEventHandler DocumentRepository_RetrieveDocumentSetCompleted;
    
    /// <remarks/>
    public event DocumentRepository_ProvideAndRegisterDocumentSetbCompletedEventHandler DocumentRepository_ProvideAndRegisterDocumentSetbCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ihe:iti:2007:RetrieveDocumentSet", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("RetrieveDocumentSetResponse", Namespace="urn:ihe:iti:xds-b:2007")]
    public RetrieveDocumentSetResponseType DocumentRepository_RetrieveDocumentSet([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:ihe:iti:xds-b:2007")] [System.Xml.Serialization.XmlArrayItemAttribute("DocumentRequest", IsNullable=false)] RetrieveDocumentSetRequestTypeDocumentRequest[] RetrieveDocumentSetRequest) {
        object[] results = this.Invoke("DocumentRepository_RetrieveDocumentSet", new object[] {
                    RetrieveDocumentSetRequest});
        return ((RetrieveDocumentSetResponseType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDocumentRepository_RetrieveDocumentSet(RetrieveDocumentSetRequestTypeDocumentRequest[] RetrieveDocumentSetRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DocumentRepository_RetrieveDocumentSet", new object[] {
                    RetrieveDocumentSetRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public RetrieveDocumentSetResponseType EndDocumentRepository_RetrieveDocumentSet(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((RetrieveDocumentSetResponseType)(results[0]));
    }
    
    /// <remarks/>
    public void DocumentRepository_RetrieveDocumentSetAsync(RetrieveDocumentSetRequestTypeDocumentRequest[] RetrieveDocumentSetRequest) {
        this.DocumentRepository_RetrieveDocumentSetAsync(RetrieveDocumentSetRequest, null);
    }
    
    /// <remarks/>
    public void DocumentRepository_RetrieveDocumentSetAsync(RetrieveDocumentSetRequestTypeDocumentRequest[] RetrieveDocumentSetRequest, object userState) {
        if ((this.DocumentRepository_RetrieveDocumentSetOperationCompleted == null)) {
            this.DocumentRepository_RetrieveDocumentSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocumentRepository_RetrieveDocumentSetOperationCompleted);
        }
        this.InvokeAsync("DocumentRepository_RetrieveDocumentSet", new object[] {
                    RetrieveDocumentSetRequest}, this.DocumentRepository_RetrieveDocumentSetOperationCompleted, userState);
    }
    
    private void OnDocumentRepository_RetrieveDocumentSetOperationCompleted(object arg) {
        if ((this.DocumentRepository_RetrieveDocumentSetCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DocumentRepository_RetrieveDocumentSetCompleted(this, new DocumentRepository_RetrieveDocumentSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-b", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("RegistryResponse", Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
    public RegistryResponseType DocumentRepository_ProvideAndRegisterDocumentSetb([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:ihe:iti:xds-b:2007")] ProvideAndRegisterDocumentSetRequestType ProvideAndRegisterDocumentSetRequest) {
        object[] results = this.Invoke("DocumentRepository_ProvideAndRegisterDocumentSetb", new object[] {
                    ProvideAndRegisterDocumentSetRequest});
        return ((RegistryResponseType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDocumentRepository_ProvideAndRegisterDocumentSetb(ProvideAndRegisterDocumentSetRequestType ProvideAndRegisterDocumentSetRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DocumentRepository_ProvideAndRegisterDocumentSetb", new object[] {
                    ProvideAndRegisterDocumentSetRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public RegistryResponseType EndDocumentRepository_ProvideAndRegisterDocumentSetb(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((RegistryResponseType)(results[0]));
    }
    
    /// <remarks/>
    public void DocumentRepository_ProvideAndRegisterDocumentSetbAsync(ProvideAndRegisterDocumentSetRequestType ProvideAndRegisterDocumentSetRequest) {
        this.DocumentRepository_ProvideAndRegisterDocumentSetbAsync(ProvideAndRegisterDocumentSetRequest, null);
    }
    
    /// <remarks/>
    public void DocumentRepository_ProvideAndRegisterDocumentSetbAsync(ProvideAndRegisterDocumentSetRequestType ProvideAndRegisterDocumentSetRequest, object userState) {
        if ((this.DocumentRepository_ProvideAndRegisterDocumentSetbOperationCompleted == null)) {
            this.DocumentRepository_ProvideAndRegisterDocumentSetbOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocumentRepository_ProvideAndRegisterDocumentSetbOperationCompleted);
        }
        this.InvokeAsync("DocumentRepository_ProvideAndRegisterDocumentSetb", new object[] {
                    ProvideAndRegisterDocumentSetRequest}, this.DocumentRepository_ProvideAndRegisterDocumentSetbOperationCompleted, userState);
    }
    
    private void OnDocumentRepository_ProvideAndRegisterDocumentSetbOperationCompleted(object arg) {
        if ((this.DocumentRepository_ProvideAndRegisterDocumentSetbCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DocumentRepository_ProvideAndRegisterDocumentSetbCompleted(this, new DocumentRepository_ProvideAndRegisterDocumentSetbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:iti:xds-b:2007")]
public partial class RetrieveDocumentSetRequestTypeDocumentRequest {
    
    private string homeCommunityIdField;
    
    private string repositoryUniqueIdField;
    
    private string documentUniqueIdField;
    
    /// <remarks/>
    public string HomeCommunityId {
        get {
            return this.homeCommunityIdField;
        }
        set {
            this.homeCommunityIdField = value;
        }
    }
    
    /// <remarks/>
    public string RepositoryUniqueId {
        get {
            return this.repositoryUniqueIdField;
        }
        set {
            this.repositoryUniqueIdField = value;
        }
    }
    
    /// <remarks/>
    public string DocumentUniqueId {
        get {
            return this.documentUniqueIdField;
        }
        set {
            this.documentUniqueIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class QueryExpressionType {
    
    private System.Xml.XmlNode[] anyField;
    
    private string queryLanguageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string queryLanguage {
        get {
            return this.queryLanguageField;
        }
        set {
            this.queryLanguageField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NotifyActionType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public abstract partial class ActionType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class NotifyActionType : ActionType {
    
    private string notificationOptionField;
    
    private string endPointField;
    
    public NotifyActionType() {
        this.notificationOptionField = "urn:oasis:names:tc:ebxml-regrep:NotificationOptionType:ObjectRefs";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    [System.ComponentModel.DefaultValueAttribute("urn:oasis:names:tc:ebxml-regrep:NotificationOptionType:ObjectRefs")]
    public string notificationOption {
        get {
            return this.notificationOptionField;
        }
        set {
            this.notificationOptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string endPoint {
        get {
            return this.endPointField;
        }
        set {
            this.endPointField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class PersonNameType {
    
    private string firstNameField;
    
    private string middleNameField;
    
    private string lastNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string middleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class EmailAddressType {
    
    private string addressField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class TelephoneNumberType {
    
    private string areaCodeField;
    
    private string countryCodeField;
    
    private string extensionField;
    
    private string numberField;
    
    private string phoneTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string areaCode {
        get {
            return this.areaCodeField;
        }
        set {
            this.areaCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string countryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phoneType {
        get {
            return this.phoneTypeField;
        }
        set {
            this.phoneTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class PostalAddressType {
    
    private string cityField;
    
    private string countryField;
    
    private string postalCodeField;
    
    private string stateOrProvinceField;
    
    private string streetField;
    
    private string streetNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stateOrProvince {
        get {
            return this.stateOrProvinceField;
        }
        set {
            this.stateOrProvinceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string streetNumber {
        get {
            return this.streetNumberField;
        }
        set {
            this.streetNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ObjectRefListType {
    
    private ObjectRefType[] objectRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ObjectRef")]
    public ObjectRefType[] ObjectRef {
        get {
            return this.objectRefField;
        }
        set {
            this.objectRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ObjectRefType : IdentifiableType {
    
    private bool createReplicaField;
    
    public ObjectRefType() {
        this.createReplicaField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool createReplica {
        get {
            return this.createReplicaField;
        }
        set {
            this.createReplicaField = value;
        }
    }
}

/// <remarks/>

[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryObjectType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NotificationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdhocQueryType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriptionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FederationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UserType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecificationLinkType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceBindingType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryPackageType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationType))]
//[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtrinsicObjectType))]
[System.Xml.Serialization.XmlInclude(typeof(ExtrinsicObjectType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExternalLinkType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationSchemeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationNodeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AuditableEventType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AssociationType1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExternalIdentifierType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectRefType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class IdentifiableType {
    
    private SlotType1[] slotField;
    
    private string idField;
    
    private string homeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Slot")]
    public SlotType1[] Slot {
        get {
            return this.slotField;
        }
        set {
            this.slotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string home {
        get {
            return this.homeField;
        }
        set {
            this.homeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class SlotType1 {
    
    private ValueListType valueListField;
    
    private string nameField;
    
    private string slotTypeField;
    
    /// <remarks/>
    public ValueListType ValueList {
        get {
            return this.valueListField;
        }
        set {
            this.valueListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string slotType {
        get {
            return this.slotTypeField;
        }
        set {
            this.slotTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ValueListType {
    
    private string[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Value")]
    public string[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NotificationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AdhocQueryType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscriptionType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FederationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UserType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecificationLinkType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceBindingType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryPackageType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtrinsicObjectType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExternalLinkType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationSchemeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationNodeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AuditableEventType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AssociationType1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExternalIdentifierType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class RegistryObjectType : IdentifiableType {
    
    private InternationalStringType nameField;
    
    private InternationalStringType descriptionField;
    
    private VersionInfoType versionInfoField;
    
    private ClassificationType[] classificationField;
    
    private ExternalIdentifierType[] externalIdentifierField;
    
    private string lidField;
    
    private string objectTypeField;
    
    private string statusField;
    
    /// <remarks/>
    public InternationalStringType Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public InternationalStringType Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public VersionInfoType VersionInfo {
        get {
            return this.versionInfoField;
        }
        set {
            this.versionInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Classification")]
    public ClassificationType[] Classification {
        get {
            return this.classificationField;
        }
        set {
            this.classificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExternalIdentifier")]
    public ExternalIdentifierType[] ExternalIdentifier {
        get {
            return this.externalIdentifierField;
        }
        set {
            this.externalIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string lid {
        get {
            return this.lidField;
        }
        set {
            this.lidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string objectType {
        get {
            return this.objectTypeField;
        }
        set {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class InternationalStringType {
    
    private LocalizedStringType[] localizedStringField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocalizedString")]
    public LocalizedStringType[] LocalizedString {
        get {
            return this.localizedStringField;
        }
        set {
            this.localizedStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class LocalizedStringType {
    
    private string langField;
    
    private string charsetField;
    
    private string valueField;
    
    public LocalizedStringType() {
        this.charsetField = "UTF-8";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("UTF-8")]
    public string charset {
        get {
            return this.charsetField;
        }
        set {
            this.charsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class VersionInfoType {
    
    private string versionNameField;
    
    private string commentField;
    
    public VersionInfoType() {
        this.versionNameField = "1.1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1.1")]
    public string versionName {
        get {
            return this.versionNameField;
        }
        set {
            this.versionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ClassificationType : RegistryObjectType {
    
    private string classificationSchemeField;
    
    private string classifiedObjectField;
    
    private string classificationNodeField;
    
    private string nodeRepresentationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string classificationScheme {
        get {
            return this.classificationSchemeField;
        }
        set {
            this.classificationSchemeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string classifiedObject {
        get {
            return this.classifiedObjectField;
        }
        set {
            this.classifiedObjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string classificationNode {
        get {
            return this.classificationNodeField;
        }
        set {
            this.classificationNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodeRepresentation {
        get {
            return this.nodeRepresentationField;
        }
        set {
            this.nodeRepresentationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ExternalIdentifierType : RegistryObjectType {
    
    private string registryObjectField;
    
    private string identificationSchemeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string registryObject {
        get {
            return this.registryObjectField;
        }
        set {
            this.registryObjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string identificationScheme {
        get {
            return this.identificationSchemeField;
        }
        set {
            this.identificationSchemeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class NotificationType : RegistryObjectType {
    
    private IdentifiableType[] registryObjectListField;
    
    private string subscriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Identifiable", IsNullable=false)]
    public IdentifiableType[] RegistryObjectList {
        get {
            return this.registryObjectListField;
        }
        set {
            this.registryObjectListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string subscription {
        get {
            return this.subscriptionField;
        }
        set {
            this.subscriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class AdhocQueryType : RegistryObjectType {
    
    private QueryExpressionType queryExpressionField;
    
    /// <remarks/>
    public QueryExpressionType QueryExpression {
        get {
            return this.queryExpressionField;
        }
        set {
            this.queryExpressionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class SubscriptionType : RegistryObjectType {
    
    private ActionType[] itemsField;
    
    private string selectorField;
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private System.DateTime endTimeField;
    
    private bool endTimeFieldSpecified;
    
    private string notificationIntervalField;
    
    public SubscriptionType() {
        this.notificationIntervalField = "P1D";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Action", typeof(ActionType))]
    [System.Xml.Serialization.XmlElementAttribute("NotifyAction", typeof(NotifyActionType))]
    public ActionType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string selector {
        get {
            return this.selectorField;
        }
        set {
            this.selectorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startTimeSpecified {
        get {
            return this.startTimeFieldSpecified;
        }
        set {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endTimeSpecified {
        get {
            return this.endTimeFieldSpecified;
        }
        set {
            this.endTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
    [System.ComponentModel.DefaultValueAttribute("P1D")]
    public string notificationInterval {
        get {
            return this.notificationIntervalField;
        }
        set {
            this.notificationIntervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class FederationType : RegistryObjectType {
    
    private string replicationSyncLatencyField;
    
    public FederationType() {
        this.replicationSyncLatencyField = "P1D";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
    [System.ComponentModel.DefaultValueAttribute("P1D")]
    public string replicationSyncLatency {
        get {
            return this.replicationSyncLatencyField;
        }
        set {
            this.replicationSyncLatencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class RegistryType : RegistryObjectType {
    
    private string operatorField;
    
    private string specificationVersionField;
    
    private string replicationSyncLatencyField;
    
    private string catalogingLatencyField;
    
    private RegistryTypeConformanceProfile conformanceProfileField;
    
    public RegistryType() {
        this.replicationSyncLatencyField = "P1D";
        this.catalogingLatencyField = "P1D";
        this.conformanceProfileField = RegistryTypeConformanceProfile.registryLite;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string @operator {
        get {
            return this.operatorField;
        }
        set {
            this.operatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string specificationVersion {
        get {
            return this.specificationVersionField;
        }
        set {
            this.specificationVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
    [System.ComponentModel.DefaultValueAttribute("P1D")]
    public string replicationSyncLatency {
        get {
            return this.replicationSyncLatencyField;
        }
        set {
            this.replicationSyncLatencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
    [System.ComponentModel.DefaultValueAttribute("P1D")]
    public string catalogingLatency {
        get {
            return this.catalogingLatencyField;
        }
        set {
            this.catalogingLatencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(RegistryTypeConformanceProfile.registryLite)]
    public RegistryTypeConformanceProfile conformanceProfile {
        get {
            return this.conformanceProfileField;
        }
        set {
            this.conformanceProfileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public enum RegistryTypeConformanceProfile {
    
    /// <remarks/>
    registryFull,
    
    /// <remarks/>
    registryLite,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UserType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class PersonType : RegistryObjectType {
    
    private PostalAddressType[] addressField;
    
    private PersonNameType personNameField;
    
    private TelephoneNumberType[] telephoneNumberField;
    
    private EmailAddressType[] emailAddressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Address")]
    public PostalAddressType[] Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public PersonNameType PersonName {
        get {
            return this.personNameField;
        }
        set {
            this.personNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TelephoneNumber")]
    public TelephoneNumberType[] TelephoneNumber {
        get {
            return this.telephoneNumberField;
        }
        set {
            this.telephoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EmailAddress")]
    public EmailAddressType[] EmailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class UserType : PersonType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class SpecificationLinkType : RegistryObjectType {
    
    private InternationalStringType usageDescriptionField;
    
    private string[] usageParameterField;
    
    private string serviceBindingField;
    
    private string specificationObjectField;
    
    /// <remarks/>
    public InternationalStringType UsageDescription {
        get {
            return this.usageDescriptionField;
        }
        set {
            this.usageDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsageParameter")]
    public string[] UsageParameter {
        get {
            return this.usageParameterField;
        }
        set {
            this.usageParameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string serviceBinding {
        get {
            return this.serviceBindingField;
        }
        set {
            this.serviceBindingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string specificationObject {
        get {
            return this.specificationObjectField;
        }
        set {
            this.specificationObjectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ServiceBindingType : RegistryObjectType {
    
    private SpecificationLinkType[] specificationLinkField;
    
    private string serviceField;
    
    private string accessURIField;
    
    private string targetBindingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SpecificationLink")]
    public SpecificationLinkType[] SpecificationLink {
        get {
            return this.specificationLinkField;
        }
        set {
            this.specificationLinkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string accessURI {
        get {
            return this.accessURIField;
        }
        set {
            this.accessURIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string targetBinding {
        get {
            return this.targetBindingField;
        }
        set {
            this.targetBindingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ServiceType : RegistryObjectType {
    
    private ServiceBindingType[] serviceBindingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServiceBinding")]
    public ServiceBindingType[] ServiceBinding {
        get {
            return this.serviceBindingField;
        }
        set {
            this.serviceBindingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class RegistryPackageType : RegistryObjectType {
    
    private IdentifiableType[] registryObjectListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Identifiable", IsNullable=false)]
    public IdentifiableType[] RegistryObjectList {
        get {
            return this.registryObjectListField;
        }
        set {
            this.registryObjectListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class OrganizationType : RegistryObjectType {
    
    private PostalAddressType[] addressField;
    
    private TelephoneNumberType[] telephoneNumberField;
    
    private EmailAddressType[] emailAddressField;
    
    private string parentField;
    
    private string primaryContactField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Address")]
    public PostalAddressType[] Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TelephoneNumber")]
    public TelephoneNumberType[] TelephoneNumber {
        get {
            return this.telephoneNumberField;
        }
        set {
            this.telephoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EmailAddress")]
    public EmailAddressType[] EmailAddress {
        get {
            return this.emailAddressField;
        }
        set {
            this.emailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string parent {
        get {
            return this.parentField;
        }
        set {
            this.parentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string primaryContact {
        get {
            return this.primaryContactField;
        }
        set {
            this.primaryContactField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ExtrinsicObjectType : RegistryObjectType {
    
    private VersionInfoType contentVersionInfoField;
    
    private string mimeTypeField;
    
    private bool isOpaqueField;
    
    public ExtrinsicObjectType() {
        this.mimeTypeField = "application/octet-stream";
        this.isOpaqueField = false;
    }
    
    /// <remarks/>
    public VersionInfoType ContentVersionInfo {
        get {
            return this.contentVersionInfoField;
        }
        set {
            this.contentVersionInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("application/octet-stream")]
    public string mimeType {
        get {
            return this.mimeTypeField;
        }
        set {
            this.mimeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isOpaque {
        get {
            return this.isOpaqueField;
        }
        set {
            this.isOpaqueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ExternalLinkType : RegistryObjectType {
    
    private string externalURIField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string externalURI {
        get {
            return this.externalURIField;
        }
        set {
            this.externalURIField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ClassificationSchemeType : RegistryObjectType {
    
    private ClassificationNodeType[] classificationNodeField;
    
    private bool isInternalField;
    
    private string nodeTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ClassificationNode")]
    public ClassificationNodeType[] ClassificationNode {
        get {
            return this.classificationNodeField;
        }
        set {
            this.classificationNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isInternal {
        get {
            return this.isInternalField;
        }
        set {
            this.isInternalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string nodeType {
        get {
            return this.nodeTypeField;
        }
        set {
            this.nodeTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class ClassificationNodeType : RegistryObjectType {
    
    private ClassificationNodeType[] classificationNodeField;
    
    private string parentField;
    
    private string codeField;
    
    private string pathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ClassificationNode")]
    public ClassificationNodeType[] ClassificationNode {
        get {
            return this.classificationNodeField;
        }
        set {
            this.classificationNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string parent {
        get {
            return this.parentField;
        }
        set {
            this.parentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class AuditableEventType : RegistryObjectType {
    
    private ObjectRefListType affectedObjectsField;
    
    private string eventTypeField;
    
    private System.DateTime timestampField;
    
    private string userField;
    
    private string requestIdField;
    
    /// <remarks/>
    public ObjectRefListType affectedObjects {
        get {
            return this.affectedObjectsField;
        }
        set {
            this.affectedObjectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string eventType {
        get {
            return this.eventTypeField;
        }
        set {
            this.eventTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string requestId {
        get {
            return this.requestIdField;
        }
        set {
            this.requestIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
public partial class AssociationType1 : RegistryObjectType {
    
    private string associationTypeField;
    
    private string sourceObjectField;
    
    private string targetObjectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string associationType {
        get {
            return this.associationTypeField;
        }
        set {
            this.associationTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string sourceObject {
        get {
            return this.sourceObjectField;
        }
        set {
            this.sourceObjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string targetObject {
        get {
            return this.targetObjectField;
        }
        set {
            this.targetObjectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
public partial class RegistryRequestType {
    
    private SlotType1[] requestSlotListField;
    
    private string idField;
    
    private string commentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Slot", Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0", IsNullable=false)]
    public SlotType1[] RequestSlotList {
        get {
            return this.requestSlotListField;
        }
        set {
            this.requestSlotListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
[System.Xml.Serialization.XmlTypeAttribute("ProvideAndRegisterDocumentSetRequest", Namespace="urn:ihe:iti:xds-b:2007",AnonymousType=false)]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ihe:iti:xds-b:2007", AnonymousType = false)]
[System.Xml.Serialization.XmlRoot(Namespace = "urn:ihe:iti:xds-b:2007")]

public partial class ProvideAndRegisterDocumentSetRequestType
{
    
    private SubmitObjectsRequest submitObjectsRequestField;
    
    private ProvideAndRegisterDocumentSetRequestTypeDocument[] documentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0")]
    public SubmitObjectsRequest SubmitObjectsRequest {
        get {
            return this.submitObjectsRequestField;
        }
        set {
            this.submitObjectsRequestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Document")]
    //[System.Xml.Serialization.XmlArrayItem(typeof(ProvideAndRegisterDocumentSetRequestTypeDocument), ElementName = "Document")]
    public ProvideAndRegisterDocumentSetRequestTypeDocument[] Document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false, Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0")]
public partial class SubmitObjectsRequest : RegistryRequestType {
    
    private IdentifiableType[] registryObjectListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0")]
    [System.Xml.Serialization.XmlArrayItemAttribute("Identifiable", IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItem( typeof(ExtrinsicObjectType), ElementName="ExtrinsicObject")]
    [System.Xml.Serialization.XmlArrayItem(typeof(ClassificationType), ElementName = "Classification")]
    [System.Xml.Serialization.XmlArrayItem(typeof(RegistryPackageType), ElementName = "RegistryPackage")]
    [System.Xml.Serialization.XmlArrayItem(typeof(AssociationType1), ElementName = "Association")]
    public IdentifiableType[] RegistryObjectList {
        get {
            return this.registryObjectListField;
        }
        set {
            this.registryObjectListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:iti:xds-b:2007")]
public partial class ProvideAndRegisterDocumentSetRequestTypeDocument {
    
    private string idField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="RegistryResponse",Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
public partial class RegistryResponseType {
    
    private SlotType1[] responseSlotListField;
    
    private RegistryErrorList registryErrorListField;
    
    private string statusField;
    
    private string requestIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Slot", Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0", IsNullable=false)]
    public SlotType1[] ResponseSlotList {
        get {
            return this.responseSlotListField;
        }
        set {
            this.responseSlotListField = value;
        }
    }
    
    /// <remarks/>
    public RegistryErrorList RegistryErrorList {
        get {
            return this.registryErrorListField;
        }
        set {
            this.registryErrorListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string requestId {
        get {
            return this.requestIdField;
        }
        set {
            this.requestIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
public partial class RegistryErrorList {
    
    private RegistryError[] registryErrorField;
    
    private string highestSeverityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RegistryError")]
    public RegistryError[] RegistryError {
        get {
            return this.registryErrorField;
        }
        set {
            this.registryErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string highestSeverity {
        get {
            return this.highestSeverityField;
        }
        set {
            this.highestSeverityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
public partial class RegistryError {
    
    private string codeContextField;
    
    private string errorCodeField;
    
    private string severityField;
    
    private string locationField;
    
    private string valueField;
    
    public RegistryError() {
        this.severityField = "urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codeContext {
        get {
            return this.codeContextField;
        }
        set {
            this.codeContextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string errorCode {
        get {
            return this.errorCodeField;
        }
        set {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    [System.ComponentModel.DefaultValueAttribute("urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error")]
    public string severity {
        get {
            return this.severityField;
        }
        set {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:iti:xds-b:2007")]
public partial class RetrieveDocumentSetResponseType {
    
    private RegistryResponseType registryResponseField;
    
    private RetrieveDocumentSetResponseTypeDocumentResponse[] documentResponseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0")]
    public RegistryResponseType RegistryResponse {
        get {
            return this.registryResponseField;
        }
        set {
            this.registryResponseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentResponse")]
    public RetrieveDocumentSetResponseTypeDocumentResponse[] DocumentResponse {
        get {
            return this.documentResponseField;
        }
        set {
            this.documentResponseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:iti:xds-b:2007")]
public partial class RetrieveDocumentSetResponseTypeDocumentResponse {
    
    private string homeCommunityIdField;
    
    private string repositoryUniqueIdField;
    
    private string documentUniqueIdField;
    
    private string newRepositoryUniqueIdField;
    
    private string newDocumentUniqueIdField;
    
    private string mimeTypeField;
    
    private byte[] documentField;
    
    /// <remarks/>
    public string HomeCommunityId {
        get {
            return this.homeCommunityIdField;
        }
        set {
            this.homeCommunityIdField = value;
        }
    }
    
    /// <remarks/>
    public string RepositoryUniqueId {
        get {
            return this.repositoryUniqueIdField;
        }
        set {
            this.repositoryUniqueIdField = value;
        }
    }
    
    /// <remarks/>
    public string DocumentUniqueId {
        get {
            return this.documentUniqueIdField;
        }
        set {
            this.documentUniqueIdField = value;
        }
    }
    
    /// <remarks/>
    public string NewRepositoryUniqueId {
        get {
            return this.newRepositoryUniqueIdField;
        }
        set {
            this.newRepositoryUniqueIdField = value;
        }
    }
    
    /// <remarks/>
    public string NewDocumentUniqueId {
        get {
            return this.newDocumentUniqueIdField;
        }
        set {
            this.newDocumentUniqueIdField = value;
        }
    }
    
    /// <remarks/>
    public string mimeType {
        get {
            return this.mimeTypeField;
        }
        set {
            this.mimeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void DocumentRepository_RetrieveDocumentSetCompletedEventHandler(object sender, DocumentRepository_RetrieveDocumentSetCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DocumentRepository_RetrieveDocumentSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DocumentRepository_RetrieveDocumentSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public RetrieveDocumentSetResponseType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((RetrieveDocumentSetResponseType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void DocumentRepository_ProvideAndRegisterDocumentSetbCompletedEventHandler(object sender, DocumentRepository_ProvideAndRegisterDocumentSetbCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DocumentRepository_ProvideAndRegisterDocumentSetbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DocumentRepository_ProvideAndRegisterDocumentSetbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public RegistryResponseType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((RegistryResponseType)(this.results[0]));
        }
    }
}
}
